// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Zi0V2KasKUN83rCdtXObCBIUKn2viUs',
    appId: '1:804986233130:web:5c646bb42a53cc45aa3e53',
    messagingSenderId: '804986233130',
    projectId: 'studyhub-33b35',
    authDomain: 'studyhub-33b35.firebaseapp.com',
    storageBucket: 'studyhub-33b35.firebasestorage.app',
    measurementId: 'G-5W59RB978K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWgo1n8FTKF__buWBqfEJ7KDofU-QTFU',
    appId: '1:804986233130:android:e7630563befa3a06aa3e53',
    messagingSenderId: '804986233130',
    projectId: 'studyhub-33b35',
    storageBucket: 'studyhub-33b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMbsb9PGbJlW0DKyCMSTBL9-AoaTwX0mg',
    appId: '1:804986233130:ios:7bc661efce453226aa3e53',
    messagingSenderId: '804986233130',
    projectId: 'studyhub-33b35',
    storageBucket: 'studyhub-33b35.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMbsb9PGbJlW0DKyCMSTBL9-AoaTwX0mg',
    appId: '1:804986233130:ios:7bc661efce453226aa3e53',
    messagingSenderId: '804986233130',
    projectId: 'studyhub-33b35',
    storageBucket: 'studyhub-33b35.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Zi0V2KasKUN83rCdtXObCBIUKn2viUs',
    appId: '1:804986233130:web:7a3e617be01a18ccaa3e53',
    messagingSenderId: '804986233130',
    projectId: 'studyhub-33b35',
    authDomain: 'studyhub-33b35.firebaseapp.com',
    storageBucket: 'studyhub-33b35.firebasestorage.app',
    measurementId: 'G-94GYHS9R3T',
  );
}
