class AppConstants {
  static final List<Map<String, dynamic>> egyptianUniversities = [

    // ══════════════════════════════════════════════════════
    //  حكومية — القاهرة الكبرى
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'جامعة القاهرة', 'nameEn': 'Cairo University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية العلاج الطبيعي', 'nameEn': 'Faculty of Physical Therapy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية الاقتصاد والعلوم السياسية', 'nameEn': 'Faculty of Economics & Political Science', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الإعلام', 'nameEn': 'Faculty of Mass Communication', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية الألسن', 'nameEn': 'Faculty of Al-Alsun (Languages)', 'years': 4},
        {'nameAr': 'كلية دار العلوم', 'nameEn': 'Faculty of Dar Al-Ulum', 'years': 4},
        {'nameAr': 'كلية الفنون الجميلة', 'nameEn': 'Faculty of Fine Arts', 'years': 4},
        {'nameAr': 'معهد التخطيط القومي', 'nameEn': 'Institute of National Planning', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
        {'nameAr': 'كلية التربية البدنية', 'nameEn': 'Faculty of Physical Education', 'years': 4},
        {'nameAr': 'كلية الخدمة الاجتماعية', 'nameEn': 'Faculty of Social Work', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة عين شمس', 'nameEn': 'Ain Shams University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية العلاج الطبيعي', 'nameEn': 'Faculty of Physical Therapy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية الألسن', 'nameEn': 'Faculty of Al-Alsun (Languages)', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية البنات للآداب والعلوم والتربية', 'nameEn': 'Faculty of Girls (Arts, Science & Education)', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة حلوان', 'nameEn': 'Helwan University',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية الفنون الجميلة', 'nameEn': 'Faculty of Fine Arts', 'years': 4},
        {'nameAr': 'كلية الفنون التطبيقية', 'nameEn': 'Faculty of Applied Arts', 'years': 4},
        {'nameAr': 'كلية الموسيقى والدراما', 'nameEn': 'Faculty of Music & Drama', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التجارة والأعمال', 'nameEn': 'Faculty of Commerce & Business Administration', 'years': 4},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الخدمة الاجتماعية', 'nameEn': 'Faculty of Social Work', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التربية الرياضية للرجال', 'nameEn': 'Faculty of Physical Education (Men)', 'years': 4},
        {'nameAr': 'كلية التربية الرياضية للبنات', 'nameEn': 'Faculty of Physical Education (Women)', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
      ],
    },

    // ══════════════════════════════════════════════════════
    //  حكومية — الدلتا والقناة
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'جامعة الإسكندرية', 'nameEn': 'Alexandria University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية العلاج الطبيعي', 'nameEn': 'Faculty of Physical Therapy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'معهد الدراسات والبحوث البيئية', 'nameEn': 'Institute of Environmental Studies', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
        {'nameAr': 'كلية الفنون الجميلة', 'nameEn': 'Faculty of Fine Arts', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة المنصورة', 'nameEn': 'Mansoura University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية العلاج الطبيعي', 'nameEn': 'Faculty of Physical Therapy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة طنطا', 'nameEn': 'Tanta University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة الزقازيق', 'nameEn': 'Zagazig University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التربية البدنية', 'nameEn': 'Faculty of Physical Education', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية الخدمة الاجتماعية', 'nameEn': 'Faculty of Social Work', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة بنها', 'nameEn': 'Benha University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة بشبرا', 'nameEn': 'Faculty of Engineering (Shoubra)', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة كفر الشيخ', 'nameEn': 'Kafr El-Sheikh University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية الصيد وتكنولوجيا الأسماك', 'nameEn': 'Faculty of Aquatic & Fisheries Sciences', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة دمياط', 'nameEn': 'Damietta University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة بورسعيد', 'nameEn': 'Port Said University',
      'faculties': [
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية الفنون التطبيقية', 'nameEn': 'Faculty of Applied Arts', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة قناة السويس', 'nameEn': 'Suez Canal University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الملاحة والتكنولوجيا', 'nameEn': 'Faculty of Maritime Studies & Technology', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
      ],
    },

    // ══════════════════════════════════════════════════════
    //  حكومية — الصعيد
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'جامعة أسيوط', 'nameEn': 'Assiut University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
        {'nameAr': 'كلية خدمة المجتمع', 'nameEn': 'Faculty of Community Service', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة المنيا', 'nameEn': 'Minia University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الفنون الجميلة', 'nameEn': 'Faculty of Fine Arts', 'years': 4},
        {'nameAr': 'كلية الألسن', 'nameEn': 'Faculty of Al-Alsun (Languages)', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة سوهاج', 'nameEn': 'Sohag University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة قنا (جنوب الوادي)', 'nameEn': 'South Valley University (Qena)',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الألسن', 'nameEn': 'Faculty of Al-Alsun', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة أسوان', 'nameEn': 'Aswan University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الخدمة الاجتماعية', 'nameEn': 'Faculty of Social Work', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة الفيوم', 'nameEn': 'Fayoum University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الآثار', 'nameEn': 'Faculty of Archaeology', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
        {'nameAr': 'كلية الخدمة الاجتماعية', 'nameEn': 'Faculty of Social Work', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
      ],
    },

    // ══════════════════════════════════════════════════════
    //  حكومية — الحدود والقناة
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'جامعة سيناء', 'nameEn': 'Sinai University (Government)',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية السياحة والفنادق', 'nameEn': 'Faculty of Tourism & Hotels', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة قناة السويس (الإسماعيلية)', 'nameEn': 'Suez University',
      'faculties': [
        {'nameAr': 'كلية الهندسة البترولية', 'nameEn': 'Faculty of Petroleum & Mining Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
      ],
    },

    // ══════════════════════════════════════════════════════
    //  الأزهر
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'جامعة الأزهر (القاهرة)', 'nameEn': 'Al-Azhar University (Cairo)',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الشريعة والقانون', 'nameEn': 'Faculty of Sharia & Law', 'years': 4},
        {'nameAr': 'كلية أصول الدين', 'nameEn': 'Faculty of Islamic Theology', 'years': 4},
        {'nameAr': 'كلية اللغة العربية', 'nameEn': 'Faculty of Arabic Language', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية الدراسات الإسلامية والعربية للبنات', 'nameEn': 'Faculty of Islamic & Arabic Studies (Women)', 'years': 4},
        {'nameAr': 'كلية الطب للبنات', 'nameEn': 'Faculty of Medicine (Women)', 'years': 6},
      ],
    },
    {
      'nameAr': 'جامعة الأزهر (أسيوط)', 'nameEn': 'Al-Azhar University (Assiut)',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الشريعة والقانون', 'nameEn': 'Faculty of Sharia & Law', 'years': 4},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية أصول الدين', 'nameEn': 'Faculty of Islamic Theology', 'years': 4},
        {'nameAr': 'كلية اللغة العربية', 'nameEn': 'Faculty of Arabic Language', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
      ],
    },

    // ══════════════════════════════════════════════════════
    //  تكنولوجية وتقنية
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'جامعة العلوم التطبيقية والتكنولوجيا', 'nameEn': 'Arab Academy for Science, Technology & Maritime Transport (AASTMT)',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'College of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'College of Computing & Information Technology', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'College of Business Administration', 'years': 4},
        {'nameAr': 'كلية النقل البحري', 'nameEn': 'College of Maritime Transport', 'years': 4},
        {'nameAr': 'كلية الفنون والتصميم', 'nameEn': 'College of Arts & Design', 'years': 4},
        {'nameAr': 'كلية اللغات والترجمة', 'nameEn': 'College of Language & Translation', 'years': 4},
      ],
    },
    {
      'nameAr': 'الأكاديمية العربية للعلوم والتكنولوجيا', 'nameEn': 'Arab Academy for Maritime Transport',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية الحوسبة ونظم المعلومات', 'nameEn': 'Faculty of Computing & Information Systems', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال والتكنولوجيا', 'nameEn': 'Faculty of Business & Technology Management', 'years': 4},
      ],
    },

    // ══════════════════════════════════════════════════════
    //  خاصة — كبرى
    // ══════════════════════════════════════════════════════
    {
      'nameAr': 'الجامعة الأمريكية بالقاهرة (AUC)', 'nameEn': 'American University in Cairo (AUC)',
      'faculties': [
        {'nameAr': 'كلية الهندسة والعلوم التطبيقية', 'nameEn': 'School of Sciences & Engineering', 'years': 4},
        {'nameAr': 'كلية الأعمال', 'nameEn': 'School of Business', 'years': 4},
        {'nameAr': 'كلية الإنسانيات والعلوم الاجتماعية', 'nameEn': 'School of Humanities & Social Sciences', 'years': 4},
        {'nameAr': 'كلية الدراسات العليا في التعليم', 'nameEn': 'Graduate School of Education', 'years': 4},
      ],
    },
    {
      'nameAr': 'الجامعة البريطانية في مصر (BUE)', 'nameEn': 'British University in Egypt (BUE)',
      'faculties': [
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الحوسبة وتكنولوجيا المعلومات', 'nameEn': 'Faculty of Computing & IT', 'years': 4},
        {'nameAr': 'كلية الإنسانيات والعلوم الاجتماعية', 'nameEn': 'Faculty of Humanities & Social Sciences', 'years': 4},
        {'nameAr': 'كلية الفنون والتصميم', 'nameEn': 'Faculty of Arts & Design', 'years': 4},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
      ],
    },
    {
      'nameAr': 'جامعة المستقبل (FUE)', 'nameEn': 'Future University in Egypt (FUE)',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية الصيدلة والتكنولوجيا الحيوية', 'nameEn': 'Faculty of Pharmacy & Biotechnology', 'years': 5},
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 6},
        {'nameAr': 'كلية الفنون والتصميم', 'nameEn': 'Faculty of Arts & Design', 'years': 4},
        {'nameAr': 'كلية الألسن', 'nameEn': 'Faculty of Languages', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة مصر للعلوم والتكنولوجيا (MUST)', 'nameEn': 'MUST University',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية الفنون التطبيقية', 'nameEn': 'Faculty of Applied Arts', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة أكتوبر للعلوم الحديثة والآداب (MSA)', 'nameEn': 'MSA University',
      'faculties': [
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computing & Information Technology', 'years': 4},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الفنون والتصميم', 'nameEn': 'Faculty of Arts & Design', 'years': 4},
        {'nameAr': 'كلية اللغات والترجمة', 'nameEn': 'Faculty of Languages & Translation', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة 6 أكتوبر', 'nameEn': '6th of October University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الفنون التطبيقية', 'nameEn': 'Faculty of Applied Arts', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة الجلالة', 'nameEn': 'Galala University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الحاسبات والذكاء الاصطناعي', 'nameEn': 'Faculty of Computers & Artificial Intelligence', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة النهضة (البهنسا)', 'nameEn': 'Nahda University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة سيناء (الخاصة)', 'nameEn': 'Sinai University (Private)',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة مصر الدولية (MIU)', 'nameEn': 'Misr International University (MIU)',
      'faculties': [
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computer Science', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الألسن', 'nameEn': 'Faculty of Languages', 'years': 4},
        {'nameAr': 'كلية الإعلام', 'nameEn': 'Faculty of Mass Communication', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة فاروس', 'nameEn': 'Pharos University in Alexandria',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الحاسبات وتكنولوجيا المعلومات', 'nameEn': 'Faculty of Computers & IT', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الفنون والتصميم', 'nameEn': 'Faculty of Arts & Design', 'years': 4},
        {'nameAr': 'كلية العلاج الطبيعي', 'nameEn': 'Faculty of Physical Therapy', 'years': 5},
      ],
    },
    {
      'nameAr': 'جامعة الإسكندرية الدولية (AIU)', 'nameEn': 'Alexandria International University (AIU)',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computer Science', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة الأهرام الكندية', 'nameEn': 'Ahram Canadian University (ACU)',
      'faculties': [
        {'nameAr': 'كلية الهندسة والتكنولوجيا', 'nameEn': 'Faculty of Engineering & Technology', 'years': 5},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computer Science & IT', 'years': 4},
        {'nameAr': 'كلية الفنون والتصميم', 'nameEn': 'Faculty of Arts & Design', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة العلوم والتكنولوجيا (الشروق)', 'nameEn': 'University of Science & Technology at Zewail City',
      'faculties': [
        {'nameAr': 'كلية العلوم والهندسة', 'nameEn': 'Faculty of Science & Engineering', 'years': 4},
        {'nameAr': 'كلية علوم الحياة', 'nameEn': 'Faculty of Life Sciences', 'years': 4},
        {'nameAr': 'كلية تكنولوجيا المعلومات', 'nameEn': 'Faculty of Information Technology', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة العاصمة الإدارية الجديدة', 'nameEn': 'New Administrative Capital University',
      'faculties': [
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية الذكاء الاصطناعي والبيانات', 'nameEn': 'Faculty of AI & Data Science', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business Administration', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة المنوفية الأهلية', 'nameEn': 'Menoufia National University',
      'faculties': [
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الحاسبات والذكاء الاصطناعي', 'nameEn': 'Faculty of AI & Computing', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة المنوفية', 'nameEn': 'Menoufia University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية طب الأسنان', 'nameEn': 'Faculty of Dentistry', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الحاسبات والمعلومات', 'nameEn': 'Faculty of Computers & Information', 'years': 4},
        {'nameAr': 'كلية الخدمة الاجتماعية', 'nameEn': 'Faculty of Social Work', 'years': 4},
        {'nameAr': 'كلية التربية النوعية', 'nameEn': 'Faculty of Specific Education', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة دمنهور', 'nameEn': 'Damanhur University',
      'faculties': [
        {'nameAr': 'كلية الطب', 'nameEn': 'Faculty of Medicine', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية العلوم', 'nameEn': 'Faculty of Science', 'years': 4},
        {'nameAr': 'كلية الآداب', 'nameEn': 'Faculty of Arts', 'years': 4},
        {'nameAr': 'كلية التجارة', 'nameEn': 'Faculty of Commerce', 'years': 4},
        {'nameAr': 'كلية الزراعة', 'nameEn': 'Faculty of Agriculture', 'years': 4},
        {'nameAr': 'كلية التمريض', 'nameEn': 'Faculty of Nursing', 'years': 4},
        {'nameAr': 'كلية التربية', 'nameEn': 'Faculty of Education', 'years': 4},
        {'nameAr': 'كلية الحقوق', 'nameEn': 'Faculty of Law', 'years': 4},
      ],
    },
    {
      'nameAr': 'جامعة كفر الشيخ الأهلية', 'nameEn': 'Kafr El-Sheikh National University',
      'faculties': [
        {'nameAr': 'كلية الهندسة', 'nameEn': 'Faculty of Engineering', 'years': 5},
        {'nameAr': 'كلية الصيدلة', 'nameEn': 'Faculty of Pharmacy', 'years': 5},
        {'nameAr': 'كلية الحاسبات والذكاء الاصطناعي', 'nameEn': 'Faculty of AI & Computing', 'years': 4},
        {'nameAr': 'كلية إدارة الأعمال', 'nameEn': 'Faculty of Business', 'years': 4},
      ],
    },
  ];
}